language: cpp
dist: trusty
sudo: required

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-7
      - clang-6.0

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-7

    - compiler: clan
      env: COMPILER=clang++-6.0

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi

install:
  - if [ "$COMPILER" = "g++-7" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - if [ "$COMPILER" = "clang++-6.0" ]; then export CXX="clang++-6.0" CC="clang-6.0"; fi

script:
  - cmake .
  - cmake --build . -- -j2