language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=g++-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
    - os: osx

before_install: if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update; fi

install: if [ "$COMPILER" = "g++-7" ]; then export CXX="g++-7" CC="gcc-7"; fi

script:
  - cmake .
  - cmake --build . -- -j2